version: '3'
services:
  message-broker:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - "cryptocop-network"
  cryptocop-api:
    build: ./Cryptocop.Software.API
    container_name: cryptocop-api
    environment:
      ASPNETCORE_URLS: http://+:5000
    ports:
      - "5000:5000"
    networks:
      - "cryptocop-network"
  email-service:
    build: ./cryptocop-emails
    container_name: email-service
    ports:
      - '8000:8000'
    depends_on:
      - message-broker
    networks:
      - "cryptocop-network"
  payment-service:
    build: ./cryptocop-payments
    container_name: payment-service
    ports:
      - '8001:8001'
    depends_on:
      - message-broker
    networks:
      - "cryptocop-network"

networks:
  cryptocop-network:
    driver: bridge